config/routes.rb
Rails.application.routes.draw do
  resources :story_comments
  # resources :image_comments
  # resources :images
  devise_for :users, class_name: 'FormUser',
    :controllers => {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
    }
  resources :users, only: [ :show ]
  resources :places, only: [ :show ]
  resources :stories do
    resources :cards
  end
  resources :relationships, only: [ :create, :destroy ]
  resources :story_loves, only: [ :create, :destroy ]

  resources :signed_urls, only: :index # GET the key to send file to S3
  get 'home' => 'pages#home', as: 'home'
  root 'pages#landing'
end

app/models/story_comment.rb
class StoryComment < ApplicationRecord
  belongs_to :user
  belongs_to :story
end

app/controllers/story_comments_controller.rb
class StoryCommentsController < ApplicationController
  before_action :set_story_comment, only: [:show, :edit, :update, :destroy]

  # GET /story_comments
  # GET /story_comments.json
  def index
    @story_comments = StoryComment.all
  end

  # GET /story_comments/1
  # GET /story_comments/1.json
  def show
  end

  # GET /story_comments/new
  def new
    @story_comment = StoryComment.new
  end

  # GET /story_comments/1/edit
  def edit
  end

  # POST /story_comments
  # POST /story_comments.json
  def create
    @story_comment = StoryComment.new(story_comment_params)
    @story_comment.user_id = current_user.id

    respond_to do |format|
      if @story_comment.save
        # url = "/stories/" + @story_comment.story_id.to_s
        # format.html { redirect_to @story_comment, notice: 'Story comment was successfully created.' }
        # format.json { render :show, status: :created, location: @story_comment }
        format.html { redirect_to :back}
      else
        format.html { render :new }
        format.json { render json: @story_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /story_comments/1
  # PATCH/PUT /story_comments/1.json
  def update
    respond_to do |format|
      if @story_comment.update(story_comment_params)
        format.html { redirect_to @story_comment, notice: 'Story comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @story_comment }
      else
        format.html { render :edit }
        format.json { render json: @story_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /story_comments/1
  # DELETE /story_comments/1.json
  def destroy
    @story_comment.destroy
    respond_to do |format|
      format.html { redirect_to story_comments_url, notice: 'Story comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story_comment
      @story_comment = StoryComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_comment_params
      params.require(:story_comment).permit(:user_id, :story_id, :comment)
    end
end

app/helpers/story_comments_helper.rb
module StoryCommentsHelper
end

app/views/story_comments/_form.html.erb
<%= form_for(story_comment) do |f| %>
  <% if story_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(story_comment.errors.count, "error") %> prohibited this story_comment from being saved:</h2>

      <ul>
      <% story_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :story_id %>
    <%= f.number_field :story_id %>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_field :comment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/story_comments/edit.html.erb
<h1>Editing Story Comment</h1>

<%= render 'form', story_comment: @story_comment %>

<%= link_to 'Show', @story_comment %> |
<%= link_to 'Back', story_comments_path %>

app/views/story_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Story Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Story</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @story_comments.each do |story_comment| %>
      <tr>
        <td><%= story_comment.user_id %></td>
        <td><%= story_comment.story_id %></td>
        <td><%= story_comment.comment %></td>
        <td><%= link_to 'Show', story_comment %></td>
        <td><%= link_to 'Edit', edit_story_comment_path(story_comment) %></td>
        <td><%= link_to 'Destroy', story_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Story Comment', new_story_comment_path %>

app/views/story_comments/new.html.erb
<h1>New Story Comment</h1>

<%= render 'form', story_comment: @story_comment %>

<%= link_to 'Back', story_comments_path %>

app/views/story_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @story_comment.user_id %>
</p>

<p>
  <strong>Story:</strong>
  <%= @story_comment.story_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @story_comment.comment %>
</p>

<%= link_to 'Edit', edit_story_comment_path(@story_comment) %> |
<%= link_to 'Back', story_comments_path %>