config/routes.rb
Rails.application.routes.draw do
  resources :story_comments
  # resources :image_comments
  # resources :images
  devise_for :users, class_name: 'FormUser',
    :controllers => {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
    }
  resources :users, only: [ :show ]
  resources :places, only: [ :show ]
  resources :stories do
    resources :cards
  end
  resources :relationships, only: [ :create, :destroy ]
  resources :story_loves, only: [ :create, :destroy ]

  resources :signed_urls, only: :index # GET the key to send file to S3
  get 'home' => 'pages#home', as: 'home'
  root 'pages#landing'
end

app/views/shared/_card_navigator.html.erb
<div class="side-container">
  <div class="cards-container">
    <% story.timeline.each do |card| %>
        <% if card.photo.present? %>
            <%= link_to edit_story_card_path(story, card) do %>
                <div class="card-container" id="card-<%= card.id %>">
                  <%= image_tag(card.photo) %>
                </div>
            <% end %>
        <% else %>
            <%= link_to edit_story_card_path(story, card) do %>
                <div class="card-container just-caption" id="card-<%= card.id %>">
                  <%= card.caption %>
                </div>
            <% end %> <!-- end link_to -->
        <% end %> <!-- end if -->
    <% end %> <!-- end each -->

    <% if story.timeline.empty? %>
        <div class="empty-card">
          <%= t ".empty_card" %>
        </div>
    <% end %>
    <div class="new-photo-btn-wrapper">
      <%= link_to new_story_card_path(story), class: 'new-photo btn' do %>
          <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
      <% end %>
    </div>
  </div> <!-- end cards-container -->

</div> <!-- end side-container -->