config/routes.rb
Rails.application.routes.draw do
  resources :story_comments
  # resources :image_comments
  # resources :images
  devise_for :users, class_name: 'FormUser',
    :controllers => {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
    }
  resources :users, only: [ :show ]
  resources :places, only: [ :show ]
  resources :stories do
    resources :cards
  end
  resources :relationships, only: [ :create, :destroy ]
  resources :story_loves, only: [ :create, :destroy ]

  resources :signed_urls, only: :index # GET the key to send file to S3
  get 'home' => 'pages#home', as: 'home'
  root 'pages#landing'
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :place
  belongs_to :user
  has_many :impressions, as: :impressionable
  has_many :cards, dependent: :destroy
  has_many :story_comments, -> { order "created_at DESC"}

  has_many :story_loves, class_name: 'StoryLove', dependent: :destroy
  has_many :lovers, through: :story_loves, source: :user

  attr_accessor :trending, :most_recent

  def lovers_count
    self.lovers.count
  end

  def timeline
    cards.order(created_at: :asc)
  end

  def lastest_card
    cards.order(created_at: :desc).first
  end

  def oldest_card
    timeline.first
  end

  def impressions_count
    impressions.size
  end

  def unique_impression_count
    # impressions.group(:ip_address).size gives => {'127.0.0.1'=>9, '0.0.0.0'=>1}
    # so getting keys from the hash and calculating the number of keys
    impressions.group(:ip_address).size.keys.length
  end

  def likes_count

  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :authenticate_user!, except: [ :show ]
  before_action :find_story, except: [ :new, :create ]
  before_action :authorize_user, except: [ :show, :new, :create ]

  before_action :log_impression, only: :show

  def show
    @story_comment = StoryComment.new
  end

  def new
    @story = Story.new
  end

  def create
    @place = Place.find_by name: place_params[:name], place_id: place_params[:place_id]
    if @place.nil?
      @place = Place.create place_params
    end
    @story = Story.new story_params
    @story.place = @place
    @story.user = current_user

    if @story.save
      redirect_to new_story_card_path(@story)
    else
      flash[:danger] = "Create story failed"
      redirect_to new_story_path
    end
  end

  def edit
  end

  def update
    @story.update_attributes story_params
    redirect_to edit_story_path(@story)
  end

  def destroy
    @story.destroy
    TrendingStory.fetch_to_db
    redirect_to home_path
  end

  private

  def authorize_user
    if @story.user.id != current_user.id
      redirect_to home_path
    end
  end

  def story_params
    params.require(:story).permit(:title, :featured)
  end

  def place_params
    params.require(:place).permit(:name, :place_id, :lat, :lng)
  end

  def find_story
    @story ||= Story.find_by id: params[:id]
    if @story.nil?
      redirect_to home_path
    end
  end

  def log_impression
    find_story
    if current_user
      @story.impressions.create(ip_address: request.remote_ip, user_id: current_user.id)
      # User also like that story for the recommendation (based on what user's see)
      current_user.like @story
      current_user.like @story.place
    else
      @story.impressions.create(ip_address: request.remote_ip)
    end
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
  def authorize_user?(story, user)
    user && story.user.id == user.id
  end
end

app/views/stories/_form.html.erb
<!-- HIDDEN FORM FOR AJAX PHOTO UPLOAD -->
<form action="https://<%= ENV['S3_BUCKET_NAME'] %>.s3-<%= ENV['AWS_REGION'] %>.amazonaws.com"
      method="post" enctype="multipart/form-data" class="direct-upload">
  <input type="hidden" name="key">
  <input type="hidden" name="AWSAccessKeyId" value="<%= ENV['AWS_ACCESS_KEY_ID'] %>">
  <input type="hidden" name="acl" value="public-read">
  <input type="hidden" name="policy">
  <input type="hidden" name="signature">
  <input type="hidden" name="success_action_status" value="201">
  <!-- UPLOAD ICON -->
  <div class="text-center">
    <input type="file" name="file" class="hidden-file" id="hidden-file">
    <label for="hidden-file">
      <div><%= t('stories.new.guide-upload-btn') %></div>
      <svg class="svgIcon-use" width="25" height="25" viewBox="0 0 25 25">
        <path d="M16.98 7.002h-.65a16.286 16.286 0 0 1-.257-.52c-.276-.581-.314-.66-.427-.857-.24-.417-.426-.625-.783-.625l-4.806.01c-.366-.01-.586.221-.825.647-.08.144-.153.291-.221.441l-.214.472c-.08.178-.147.32-.207.439H6.435C5.057 7.009 4 8.003 4 9.36v7.2c0 1.37 1.071 2.449 2.438 2.44h12.095A2.442 2.442 0 0 0 21 16.556v-5.55h-1v5.549c-.001.81-.645 1.444-1.467 1.444H6.435C5.622 18.004 5 17.377 5 16.561v-7.2c0-.79.596-1.351 1.435-1.351h2.74l.144-.248a8.19 8.19 0 0 0 .389-.78c-.048.108.162-.36.21-.462a5.36 5.36 0 0 1 .186-.373 1.63 1.63 0 0 1 .085-.137l4.514-.009c.022.033.048.074.076.123.094.163.132.241.391.788.087.183.148.309.21.431.085.165.16.304.236.424l.146.236h1.278l-.06-1.001z"></path>
        <path d="M12.499 15.999A3.485 3.485 0 0 1 9 12.498 3.484 3.484 0 0 1 12.499 9a3.485 3.485 0 0 1 3.499 3.499A3.485 3.485 0 0 1 12.499 16v-.001zm0-6.1c-1.411 0-2.598 1.188-2.598 2.599 0 1.412 1.187 2.601 2.598 2.601 1.411 0 2.598-1.189 2.598-2.6 0-1.41-1.187-2.6-2.598-2.6z"></path>
        <path d="M21 7V5h-1v2h-2v1h2v2h1V8h2V7z"></path>
      </svg>
    </label>
  </div>
  <!-- PROGRESS BAR -->
  <div class="progress-note"></div>
  <div class="progress" style="display: none">
    <div class="progress-bar progress-bar-info progress-bar-striped"
         role="progressbar">
    </div>
  </div>
</form>

<!-- ACTUAL FORM FOR STORY -->
<%= form_for @story do |f| %>
    <div class="col-md-8">
      <div class="featured image-preview">
        <%= image_tag(@story.featured) if @story.featured.present? %>
      </div>
    </div>

    <div class="col-md-4 form-new-story">
      <div class="form-group form-title">
        <label for="title"><%= t('stories.form.title') %> <span class="required-label">*</span></label>
        <%= f.text_field :title, placeholder: t(".title"), value: @story.title, :class => "form-control", :required => true %>
      </div>

      <div class="form-group form-place">
        <label for="place"><%= t('stories.form.place') %></label>
        <input type="text" name="place[name]" placeholder="<%= t('stories.form.place_name') %>"
               id="place" class="form-control"
               value="<%= @story.place.name if @story.place.present? %>">
          <input type="hidden" name="place[lat]" id="place-lat" value="<%= @story.place.lat if @story.place.present? %>">
          <input type="hidden" name="place[lng]" id="place-lng" value="<%= @story.place.lng if @story.place.present? %>">
          <input type="hidden" name="place[place_id]" id="place-id" value="<%= @story.place.place_id if @story.place.present?%>">
      </div>
      <%= f.hidden_field :featured %>
      <div class="form-group">
        <%= f.submit t('stories.form.create'), :class => "btn btn-default submit-btn" %>
      </div>
    </div>
<% end %>


<script>
    $(document).on('turbolinks:load', function () {
        $(function () {
            $('input#place').geocomplete().bind("geocode:result", function(event, result){
              $("input#place-lat").val(result.geometry.location.lat());
              $("input#place-lng").val(result.geometry.location.lng());
              $("input#place-id").val(result.place_id)
            });

            $('.direct-upload').each(function () {
                var form = $(this)
                $(this).fileupload({
                    url: form.attr('action'),
                    type: 'POST',
                    autoUpload: true,
                    dataType: 'xml', // This is really important as s3 gives us back the url of the file in a XML document
                    add: function (event, data) {
                        $(".form-new-story").fadeIn();
                        $('.progress-bar').css('width', 0);
                        $(".intro-wrapper").removeClass("margin-top-15-percent");

                        $.ajax({
                            url: "/signed_urls",
                            type: 'GET',
                            dataType: 'json',
                            data: {doc: {title: data.files[0].name}}, // send the file name to the server so it can generate the key param
                            async: false,
                            success: function (data) {
                                // Now that we have our data, we update the form so it contains all
                                // the needed data to sign the request
                                form.find('input[name=key]').val(data.key)
                                form.find('input[name=policy]').val(data.policy)
                                form.find('input[name=signature]').val(data.signature)
                            }
                        })
                        data.submit();
                    },
                    send: function (e, data) {
                        // Remove the old photo
                        $('.featured img').remove();

                        $('.progress').fadeIn();
                    },
                    progress: function (e, data) {
                        // This is what makes everything really cool, thanks to that callback
                        // you can now update the progress bar based on the upload progress
                        $(".progress-note").text("アップロードされた合計" +data.total/1000+ "KB のうち " + data.loaded/1000 + "KB");
                        console.log("アップロードされた合計" +data.total/1000+ "KB のうち " + data.loaded/1000 + "KB");
                        var percent = Math.round((data.loaded / data.total) * 100);
                        $('.progress-bar').css('width', percent + '%')
                    },
                    fail: function (e, data) {
                        console.log('fail')
                    },
                    success: function (data) {
                        // Here we get the file url on s3 in an xml doc
                        var url = $(data).find('Location').text()

                        $('#story_featured').val(url) // Update the real input in the other form

//                        $('.progress').toggle();

                        $(".progress-note").text("アップロードが完了しました。 保存する準備ができましす。")

                        // Append the new photo
                        $('.featured')
                            .append("<img src=" + url + ">")
                    },
                    done: function (event, data) {
                        // $('.progress-bar').removeClass('progress-bar-info')
                        //   .addClass('progress-bar-success')
//                        $('.progress').fadeOut(1000, function () {
//                            $('.progress-bar').css('width', 0)
//                        })
                    },
                })

            })
        })

    })
</script>

app/views/stories/_story.html.erb
<div class="story-wrapper">
  <div class="uploader-info">
    <%= link_to user_path(id: story.user_id), :class => "profile-pic" do %>
        <div class="profile-pic-img" style="background-image: url(<%= story.user.avatar || "//imghtlak.mmtcdn.com/blog/sites/default/files/styles/47x47/public/pictures/picture-155481-1480931403.png" %>);"></div>
    <% end %>
    </a>
    <div class="left">
      <%= link_to user_path(id: story.user_id), :class => "name" do %>
        <%= truncate(story.user.name || story.user.email, length: 30) %>
      <% end %>
    </div>
    <div class="right" id="parent">
      <span class="date-upload" id="hover-content"><%= story.created_at %></span>
      <%= distance_of_time_in_words_to_now(story.created_at) %>
    </div>
  </div>
  <div class="large-headline">
    <%= truncate story.title, length: 50 %>
  </div>
  <%= link_to story_path(story) do %>
      <div class="story-cover" style="background-image: url(<%= story.featured %>);">
      </div>
  <% end %>

  <%= link_to story_path(story) do %>
      <p class="read-more caption">
        <%= story.oldest_card.caption if story.oldest_card.present? &&
            story.oldest_card.caption.present? %>...
      </p>
  <% end %>

  <div class="story-action">
    <%= render partial: "shared/loves/loves_count", locals: {story: story} %>
    <% if story.trending %>
        <div class="trending">
          <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
          <span class="trending-text"> <%= t('home.trending') %></span>
        </div>
    <% end %>
    <%= render partial: "shared/views/views_count", locals: {story: story} %>
  </div>
</div>

app/views/stories/_story_square.html.erb
<div class="col-sm-4 story-item">
  <div class="story-wrapper" style="background-image: url(<%= story.featured %>);">
    <%= link_to "", story_path(story), class: 'story-detail-link' %>
    <div class="uploader-area">
      <a href="#uploader-profile">
        <div class="uploader-wrapper">
          <div class="profile-pic" style="background-image: url(<%= story.user.avatar || "//imghtlak.mmtcdn.com/blog/sites/default/files/styles/47x47/public/pictures/picture-155481-1480931403.png" %>);"></div>
          <p class="name"><%= story.user.name || story.user.email %></p>
        </div>
      </a>
    </div>
    <p class="story-title"><%= truncate story.title, length: 30 %></p>
    <div class="story-stat">
      <div class="like-count">
        <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
        <%= story.lovers_count %>
      </div>
      <div class="views-count">
        <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
        <%= story.unique_impression_count %>
      </div>
    </div>
  </div>
</div>

app/views/stories/_story_thumbnail.html.erb
<div class="col-sm-<%= col_width || 6 %> story-item story-thumbnail">
  <div class="story-wrapper" style="background-image: url(<%= story.featured %>);">
    <%= link_to "", story_path(story), class: 'story-detail-link' %>
    <div class="uploader-area">
      <a href="#uploader-profile">
        <div class="uploader-wrapper">
          <div class="profile-pic" style="background-image: url(<%= story.user.avatar || "//imghtlak.mmtcdn.com/blog/sites/default/files/styles/47x47/public/pictures/picture-155481-1480931403.png" %>);"></div>
          <p class="name"><%= story.user.name || story.user.email %></p>
        </div>
      </a>
    </div>
    <a href="<%= story_path(story) %>">
      <p class="story-title"><%= truncate story.title, length: 30 %></p>
    </a>
    <div class="story-stat">
      <div class="like-count">
        <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
        <%= story.lovers_count %>
      </div>
      <div class="views-count">
        <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
        <%= story.unique_impression_count %>
      </div>
    </div>
  </div>
</div>

app/views/stories/edit.html.erb
<h1>Edit story</h1>
<div class="row">
  <div class="col-md-4">
    <%= render partial: 'shared/card_navigator', locals: { story: @story } %>
  </div>

  <div class="col-md-8">
    <h2><%= @story.title %></h2>

    <%= render 'form', locals: { story: @story } %>
  </div>
</div>

app/views/stories/new.html.erb
<div class="container full-height">

  <div class="intro-wrapper margin-top-15-percent">
    <h1><%= t('stories.new.new-story') %></h1>
    <h3 class="text-center "><%= t('stories.new.guide') %></h3>
  </div>
  <%= render 'form', locals: {story: @story} %>
</div>

app/views/stories/show.html.erb
<div class="container image-show-page" style="padding: 0">
  <!-- start slideshow container -->
  <div class="col-md-12 slideshow-container">
    <a href="javascript:history.back()" class="back-btn">
      <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
    </a>
    <!-- start featured -->
    <div class="mySlides fade-animation"
         style="position: absolute;
             left: 0;
             height: 100vh;
             width: 100%;">
      <div class="image-featured"
           style="background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url(<%= @story.featured if @story.featured.present? %>);
               width:100%">
        <div class="headline-wrapper">
          <div class="large-headline"><%= @story.title %></div>
          <div class="small-headline"><%= @story.place.name %></div>
          <div class="story-wrapper">
            <div class="story-action">
              <!-- <div class="like-count">
                <span class="glyphicon glyphicon-heart-empty like-btn" aria-hidden="true"></span>
                <span class="like-text"> <%= @story.liked_by_count %> <%# t('home.like') %></span>
              </div> -->
              <%= render "shared/loves/stats" %>
              <% if @story.trending %>
                  <div class="trending">
                    <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
                    <span class="trending-text"> <%= t('home.trending') %></span>
                  </div>
              <% end %>
              <div class="comment-count">
                <span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
                <span class="comment-text"> <%= @story.story_comments.count %> <%# t('home.response') %></span>
              </div>
              <%= render partial: "shared/views/views_count", locals: {story: @story} %>
            </div>
          </div>
        </div>
      </div>

    </div>
    <!-- end featured -->

    <!-- start cards -->
    <% timeline = @story.timeline %>
    <% cards_count = timeline.size %>
    <% @story.timeline.each_with_index do |card, index| %>
        <div class="mySlides fade-animation card-container">
          <div class="numbertext"><%= index + 1 %> / <%= cards_count %></div>
          <%= image_tag card.photo, class: "#{'image-blank' if card.photo.empty?}" %>
          <% if card.caption.present? %>
              <div class="text caption <%= "just-caption" if card.photo.empty? %>"><%= card.caption %></div>
          <% end %>
        </div>
    <% end %>
    <!-- end cards -->

    <!-- start recommendations -->
    <div class="mySlides fade-animation"
         style="position: absolute;
             left: 0;
             height: 100vh;
             width: 100%;">
       <div class="image-featured"
            style="background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5));
                width:100%">
         <div class="headline-wrapper recommendations-wrapper">
           <div class="large-headline">
             以上です
           </div>
           <% if user_signed_in? %>
             <!-- start recommended_stories -->
             <div class="row">
               <div class="col-sm-3">
                 <h4 class="small-headline">お勧めのストーリー</h4>
               </div>
               <% current_user.recommended_stories(3).each do |story| %>
                 <%= render partial: "stories/story_thumbnail", locals: {story: story, col_width: 3} %>
               <% end %>
             </div>
             <!-- end recommended_stories -->

              <!-- recommended_places            -->
              <div class="row">
                <div class="col-sm-3">
                  <h4 class="small-headline">お勧めの場所</h4>
                </div>
                <% current_user.recommended_places(3).each do |place| %>
                  <%= render partial: "places/place_thumbnail", locals: {place: place, col_width: 3} %>
                <% end %>
              </div>
              <!-- recommended_places -->

              <!-- recommended_users            -->
              <div class="row">
                <div class="col-sm-3">
                  <h4 class="small-headline">お勧めのウーザー</h4>
                </div>
                <% current_user.recommended_users(3).each do |user| %>
                  <%= render partial: "users/user_thumbnail", locals: {user: user, col_width: 3} %>
                <% end %>
              </div>
              <!-- recommended_users -->
           <% end %>
         </div>
       </div>
    </div>

    <!-- end recommendations -->


    <a class="prev slideshow-prev">&#10094;</a>
    <a class="next slideshow-next">&#10095;</a>
    <a class="toggle-info">
      <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
    </a>
    <br>
    <div style="text-align:center" style="display: none">
      <% (cards_count + 1).times do |i| %>
          <span class="dot slideshow-current" data-index="<%= i + 1 %>"></span>
      <% end %>
    </div>
  </div>
  <!-- end slideshow container -->

  <!-- start comment container (right part) -->
  <div class="hidden comment-container story-wrapper">
    <!-- start uploader info -->
    <div class="uploader-info">
      <%= link_to user_path(id: @story.user_id), :class => "profile-pic" do %>
          <div class="profile-pic-img" style="background-image: url(<%= @story.user.avatar || "//imghtlak.mmtcdn.com/blog/sites/default/files/styles/47x47/public/pictures/picture-155481-1480931403.png" %>);"></div>
      <% end %>
      </a>
      <div class="left">
        <%= link_to user_path(id: @story.user_id), :class => "name" do %>
            <%= truncate(@story.user.name || @story.user.email, length: 30) %>
        <% end %>

        <p class="date-upload" id="hover-content"><%= distance_of_time_in_words_to_now(@story.created_at) %></p>
      </div>
      <% if authorize_user?(@story, current_user) %>
          <div class="right">
            <div class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <span class="caret"></span></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>
                  <%= link_to t("stories.show.edit"), edit_story_path(@story) %>
                </li>
                <li><%= link_to t("stories.show.delete"), @story, method: :delete, data: {confirm: 'Are you sure?'} %></li>
              </ul>
            </div>
          </div>
      <% end %>
    </div>
    <p class="large-headline"><%= @story.title %></p>

    <!-- end uploader info -->

    <!-- start comment wrapper -->
    <div class="comment-wrapper fade-animation fade-out-animation">
      <!-- start comment form -->
      <div class="comment-form">
        <!-- <div class="avatar">-->
        <!--<div class="profile-pic-img" style="background-image: url(//imghtlak.mmtcdn.com/blog/sites/default/files/styles/47x47/public/pictures/picture-155481-1480931403.png);"></div>-->
        <!--</div> -->
        <% if current_user %>
            <div class="comment-input">
              <%= form_for(@story_comment) do |f| %>
                  <div>
                    <%= f.text_field :comment, :class => "form-control", :placeholder => "コメントを書く" %>
                    <%= f.hidden_field :story_id, :value => @story.id %>
                    <!--<div class="input-group-btn">-->
                    <%# f.submit "Send comment", :class => "btn btn-default" do %>
                    <!--<i class="glyphicon glyphicon-search"></i>-->
                    <%# end %>
                    <!--</div>-->
                  </div>
              <% end %>
            </div>
        <% end %>
      </div>
      <!-- end comment form -->

      <!-- start comment show all -->
      <div class="comment-show-all">
        <% if @story.story_comments.count>0 %>
            <div class="comment-count">
              <span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
              <%= @story.story_comments.count.to_s + " " + t("stories.show.comment") %>
            </div>
        <% end %>
        <div>
          <% @story.story_comments.order(created_at: :desc).each do |story_comment| %>
              <div class="comment-item">
                <p class="username-comment"><%= story_comment.user.name || story_comment.user.email %>
                  <span class="comment-content"><%= story_comment.comment %></span>
                </p>
              </div>
          <% end %>
        </div>
      </div>
      <!-- end comment show all -->
    </div>
    <!-- end comment wrapper -->
  </div>
  <!-- end comment container (right part) -->
</div>