config/routes.rb
Rails.application.routes.draw do
  resources :story_comments
  # resources :image_comments
  # resources :images
  devise_for :users, class_name: 'FormUser',
    :controllers => {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
    }
  resources :users, only: [ :show ]
  resources :places, only: [ :show ]
  resources :stories do
    resources :cards
  end
  resources :relationships, only: [ :create, :destroy ]
  resources :story_loves, only: [ :create, :destroy ]

  resources :signed_urls, only: :index # GET the key to send file to S3
  get 'home' => 'pages#home', as: 'home'
  root 'pages#landing'
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :story, dependent: :destroy

  # mount_uploader :photo, PhotoUploader

  # Neu prev_id == 0 thi tuc la card nay la card dau tien trong story
  def prev
    prev_id == 0 ? nil : story.cards.find(prev_id)
  end

  def prev=(aCard)
    if aCard.instance_of? Card
      self.prev_id = aCard.id
    else
      self.prev_id = aCard
    end
  end

  # Neu next_id ma la -1 thi tuc la card nay la card cuoi cung trong story
  def next
    self.next_id == -1 ? nil : self.story.cards.find(self.next_id)
  end

  # Gan gia tri cho card tiep theo. Neu bien truyen vao la 1 Card thi id cua Card
  # Neu khong thi gan luon
  def next=(aCard)
    if aCard.instance_of? Card
      self.next_id = aCard.id
    else
      self.next_id = aCard
    end
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!, except: [ :show ]
  before_action :find_story
  before_action :find_card, only: [ :edit, :update, :destroy ]
  before_action :authorize_user, except: [ :show ]

  def create
    @card = Card.new card_params
    @card.story = @story
    if @card.save
      flash[:success] = 'Create ok'
      redirect_to new_story_card_path(@story)
    else
      flash[:error] = 'Fail'
    end
  end

  def new
    @card = Card.new story: @story
  end

  def show
    @card = Card.find(params[:id])
  end

  def edit
  end

  def update
    @card.update_attributes card_params
    redirect_to edit_story_card_path(@story, @card)
  end

  def destroy
    @card.destroy
    if @story.cards.empty?
      redirect_to new_story_card_path(@story)
    else
      redirect_to edit_story_card_path(@story, @story.lastest_card)
    end
  end

  private

  def authorize_user
    find_story
    if @story.user.id != current_user.id
      redirect_to home_path
    end
  end

  def find_story
    @story ||= Story.find_by id: params[:story_id]
    if @story.nil?
      puts "nil"
      redirect_to home_path
    end
  end

  def find_card
    @card ||= Card.find_by id: params[:id]
    if @card.nil?
      redirect_to home_path
    end
  end

  def card_params
    params.require(:card).permit(:photo, :caption)
  end
end

app/views/cards/_form.html.erb
<div class="photo-upload-container">

  <div class="photo">
    <% if @card.photo.present? %>
        <%= image_tag(@card.photo) %>
    <% else %>
        <span class="img-blank"></span>
    <% end %>
  </div>

  <!-- HIDDEN FORM FOR AJAX PHOTO UPLOAD -->
  <form action="https://<%= ENV['S3_BUCKET_NAME'] %>.s3-<%= ENV['AWS_REGION'] %>.amazonaws.com"
        method="post" enctype="multipart/form-data" class="direct-upload">
    <input type="hidden" name="key">
    <input type="hidden" name="AWSAccessKeyId" value="<%= ENV['AWS_ACCESS_KEY_ID'] %>">
    <input type="hidden" name="acl" value="public-read">
    <input type="hidden" name="policy">
    <input type="hidden" name="signature">
    <input type="hidden" name="success_action_status" value="201">
    <!-- UPLOAD ICON -->
    <input type="file" name="file" class="hidden-file" id="hidden-file">
    <label for="hidden-file">
      <span class="glyphicon glyphicon-camera" aria-hidden="true"></span>
    </label>

    <!-- PROGRESS BAR -->
    <div class="progress" style="display: none">
      <div class="progress-bar progress-bar-info progress-bar-striped"
           role="progressbar">
      </div>
    </div>

  </form>
</div>
<%= form_for [@story, @card] do |f| %>
    <%= f.hidden_field :photo %>
    <textarea name="card[caption]" id="card_caption" rows="2" placeholder="<%= t('cards.new.tell-story') %>" class="caption" autofocus="true"><%= @card.caption %></textarea>
    <%= f.submit t('cards.new.create'), :class => "btn submit-btn" %>
    <% if @card.id.present? %>
        <%= link_to 'Delete', story_card_path(@story, @card), method: 'delete', :class => "btn btn-danger" %>
    <% end %>
<% end %>

<script>
    $(document).on('turbolinks:load', function () {
        $(function () {
            $('.direct-upload').each(function () {
                var form = $(this)
                $(this).fileupload({
                    url: form.attr('action'),
                    type: 'POST',
                    autoUpload: true,
                    dataType: 'xml', // This is really important as s3 gives us back the url of the file in a XML document
                    add: function (event, data) {
                        $.ajax({
                            url: "/signed_urls",
                            type: 'GET',
                            dataType: 'json',
                            data: {doc: {title: data.files[0].name}}, // send the file name to the server so it can generate the key param
                            async: false,
                            success: function (data) {
                                // Now that we have our data, we update the form so it contains all
                                // the needed data to sign the request
                                form.find('input[name=key]').val(data.key)
                                form.find('input[name=policy]').val(data.policy)
                                form.find('input[name=signature]').val(data.signature)
                            }
                        })
                        data.submit();
                    },
                    send: function (e, data) {
                        // Remove the old photo
                        $('.photo img').remove();

                        $('.progress').fadeIn();
                    },
                    progress: function (e, data) {
                        // This is what makes everything really cool, thanks to that callback
                        // you can now update the progress bar based on the upload progress
                        var percent = Math.round((data.loaded / data.total) * 100)
                        $('.progress-bar').css('width', percent + '%')
                    },
                    fail: function (e, data) {
                        console.log('fail')
                    },
                    success: function (data) {
                        // Here we get the file url on s3 in an xml doc
                        var url = $(data).find('Location').text()

                        $('#card_photo').val(url) // Update the real input in the other form

                        $('.progress').toggle();
                        // Append the new photo
                        $('.photo')
                            .html("<img src=" + url + ">")
                    },
                    done: function (event, data) {
                        // $('.progress-bar').removeClass('progress-bar-info')
                        //   .addClass('progress-bar-success')
                        $('.progress').fadeOut(1000, function () {
                            $('.progress-bar').css('width', 0)
                        })
                    },
                })

            })
        })

    })
</script>

app/views/cards/edit.html.erb
<div class="container">
  <div class="col-md-12">
    <%= link_to story_path(@story) do %>
        <h2 style="display: inline-block;"><%= @story.title %></h2>
    <% end %>
  </div>
  <div class="col-md-4 col-sm-3">
    <%= render partial: 'shared/card_navigator', locals: { story: @story } %>
  </div>
  <div class="col-md-8 story-form-wrapper">
    <%= render 'form', locals: { story: @story, card: @card } %>
  </div>
</div>

app/views/cards/new.html.erb
<div class="container">
  <div class="col-md-12">
    <%= link_to story_path(@story) do %>
        <h2 style="display: inline-block;"><%= @story.title %></h2>
    <% end %>
  </div>
  <div class="col-md-4 col-sm-3">
    <%= render partial: 'shared/card_navigator', locals: {story: @story} %>
  </div>
  <div class="col-md-8 story-form-wrapper">
    <%= render 'form', locals: {story: @story, card: @card} %>
  </div>
</div>

app/views/cards/show.html.erb
<%= @card.caption %>
<%= image_tag @card.photo %>